use_frameworks!

platform :ios, '11.0'

target 'RCMusicControlKit_Example' do
  pod 'RCMusicControlKit', :path => '../'

  target 'RCMusicControlKit_Tests' do
    inherit! :search_paths

    
  end
end
